# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simulator(object):
    def setupUi(self, Simulator):
        Simulator.setObjectName("Simulator")
        Simulator.resize(1229, 734)
        self.centralwidget = QtWidgets.QWidget(Simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 41, 881, 591))
        self.graphicsView.setObjectName("graphicsView")
        Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuools = QtWidgets.QMenu(self.menubar)
        self.menuools.setObjectName("menuools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Simulator)
        self.statusbar.setObjectName("statusbar")
        Simulator.setStatusBar(self.statusbar)

        # Toolbars
        self.toolBar_2 = QtWidgets.QToolBar(Simulator)
        self.toolBar_2.setObjectName("toolBar_2")
        Simulator.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(Simulator)
        self.toolBar_3.setObjectName("toolBar_3")
        Simulator.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar = QtWidgets.QToolBar(Simulator)
        self.toolBar.setObjectName("toolBar")
        Simulator.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        # Dock Widget and List
        self.dockWidget = QtWidgets.QDockWidget(Simulator)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")

        # List Items (Icons and Setup)
        icon_paths = [
            "images/icons8-toggle-on-90.png", "images/0.png", "images/1.png",
            "images/icons8-light-96.png", "images/icons8-logic-gate-buffer-96.png",
            "images/icons8-logic-gate-not-96.png", "images/icons8-logic-gate-and-96.png",
            "images/icons8-logic-gate-nand-96.png", "images/icons8-logic-gate-or-96.png",
            "images/icons8-logic-gate-nor-96.png", "images/icons8-logic-gate-xor-96.png",
            "images/icons8-logic-gate-xnor-96.png"
        ]

        for path in icon_paths:
            item = QtWidgets.QListWidgetItem()
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            self.listWidget.addItem(item)

        # Separators and Complex Blocks
        for _ in range(3):
            item = QtWidgets.QListWidgetItem()
            if _ == 1: # Index 13 in total
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setBold(True)
                font.setWeight(75)
                item.setFont(font)
            self.listWidget.addItem(item)

        # Complex Block Icons
        complex_icons = ["images/alu.png"]
        for path in complex_icons:
            item = QtWidgets.QListWidgetItem()
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            self.listWidget.addItem(item)

        self.verticalLayout.addWidget(self.listWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        Simulator.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        # Actions
        self.actionCut = QtWidgets.QAction(Simulator)
        self.actionCut.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon15)
        self.actionCut.setObjectName("actionCut")

        self.actionUndo = QtWidgets.QAction(Simulator)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../images/icons8-undo-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon16)
        self.actionUndo.setObjectName("actionUndo")

        self.actionRedo = QtWidgets.QAction(Simulator)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../images/icons8-redo-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon17)
        self.actionRedo.setObjectName("actionRedo")

        self.actionCopy = QtWidgets.QAction(Simulator)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon18)
        self.actionCopy.setObjectName("actionCopy")

        self.actionCursor = QtWidgets.QAction(Simulator)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../images/cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCursor.setIcon(icon19)
        self.actionCursor.setObjectName("actionCursor")

        # New actions from TEMP.py
        self.actionOpen = QtWidgets.QAction(Simulator)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Simulator)
        self.actionSave.setObjectName("actionSave")

        # Menu Assignments
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # Toolbar Assignments
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCursor)

        self.retranslateUi(Simulator)
        QtCore.QMetaObject.connectSlotsByName(Simulator)

    def retranslateUi(self, Simulator):
        _translate = QtCore.QCoreApplication.translate
        Simulator.setWindowTitle(_translate("Simulator", "MainWindow"))
        self.menuFile.setTitle(_translate("Simulator", "File "))
        self.menuEdit.setTitle(_translate("Simulator", "Edit"))
        self.menuView.setTitle(_translate("Simulator", "View"))
        self.menuools.setTitle(_translate("Simulator", "Tools"))
        self.menuHelp.setTitle(_translate("Simulator", "Help"))
        self.toolBar_2.setWindowTitle(_translate("Simulator", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("Simulator", "toolBar_3"))
        self.toolBar.setWindowTitle(_translate("Simulator", "toolBar"))
        self.dockWidget.setWindowTitle(_translate("Simulator", "Logic Gates"))

        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Simulator", "Switch"))
        item = self.listWidget.item(1)
        item.setText(_translate("Simulator", "ZERO"))
        item = self.listWidget.item(2)
        item.setText(_translate("Simulator", "ONE"))
        item = self.listWidget.item(3)
        item.setText(_translate("Simulator", "Bulb"))
        item = self.listWidget.item(4)
        # Priority: _code.py "BUF Gate" over TEMP.py "Buffer"
        item.setText(_translate("Simulator", "BUF Gate"))
        item = self.listWidget.item(5)
        item.setText(_translate("Simulator", "NOT Gate"))
        item = self.listWidget.item(6)
        item.setText(_translate("Simulator", "AND Gate"))
        item = self.listWidget.item(7)
        item.setText(_translate("Simulator", "NAND Gate"))
        item = self.listWidget.item(8)
        item.setText(_translate("Simulator", "OR Gate"))
        item = self.listWidget.item(9)
        item.setText(_translate("Simulator", "NOR Gate"))
        item = self.listWidget.item(10)
        item.setText(_translate("Simulator", "XOR Gate"))
        item = self.listWidget.item(11)
        item.setText(_translate("Simulator", "XNOR Gate"))
        item = self.listWidget.item(12)
        item.setText(_translate("Simulator", "-------------------------"))
        item = self.listWidget.item(13)
        item.setText(_translate("Simulator", "COMPLEX BLOCKS"))
        item = self.listWidget.item(14)
        item.setText(_translate("Simulator", "-------------------------"))
        item = self.listWidget.item(15)
        item.setText(_translate("Simulator", "ALU"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

        self.actionCut.setText(_translate("Simulator", "Cut"))
        self.actionCut.setToolTip(_translate("Simulator", "Cut selected objects"))
        self.actionUndo.setText(_translate("Simulator", "Undo"))
        self.actionUndo.setToolTip(_translate("Simulator", "Undo to the previous action"))
        self.actionRedo.setText(_translate("Simulator", "Redo"))
        self.actionRedo.setToolTip(_translate("Simulator", "Redo the next action"))
        self.actionCopy.setText(_translate("Simulator", "Copy"))
        self.actionCopy.setToolTip(_translate("Simulator", "Copy the selected item"))
        self.actionCursor.setText(_translate("Simulator", "Cursor"))
        self.actionCursor.setToolTip(_translate("Simulator", "Cursor"))

        self.actionOpen.setText(_translate("Simulator", "Open"))
        self.actionOpen.setShortcut(_translate("Simulator", "Ctrl+O"))
        self.actionSave.setText(_translate("Simulator", "Save"))
        self.actionSave.setShortcut(_translate("Simulator", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Simulator = QtWidgets.QMainWindow()
    ui = Ui_Simulator()
    ui.setupUi(Simulator)
    Simulator.show()
    sys.exit(app.exec_())
